### ISSUE TITLE
Printing Output

### ISSUE THREAD

**Issue by jonluntzel** [alexyuisingwu/sliding-puzzle-solver#1]
Not an issue, but I was wondering how difficult it would be to see the sequence of steps required to produce an output (have not played around with it yet)

**Comment by alexyuisingwu** [comment]
Do you mean the steps in the algorithm used to find the optimal path, or the solution itself?

The solution is printed after the solver solves the puzzle, but the algorithm's exploration of the problem state is not shown.

The algorithm used is a fairly standard IDA*, as far as I remember, and creating a visualization of that seems like it would be fairly simple. The linear conflict and Manhattan distance heuristics are intuitive enough that they should also be possible to visualize. The pattern database heuristic would be a little more challenging to visualize, but relatively simple to understand.

I haven't put much thought into visualizing these things however, so I could be wrong.

**Comment by alexyuisingwu** [comment]
You can look at https://github.com/alexyuisingwu/sliding-puzzle-solver/blob/master/src/sliding-puzzle-algorithms.js for implementation details.

It still has a lot of leftover comments/TODOs however.

**Comment by jonluntzel** [comment]
I just meant the steps of the optimal path itself, that's great! What is the largest dimensions you have been able to run it on?Also, I am having trouble using a local HTTP server - when I try to go to http://0.0.0.0:8000/, it says "This site can't be reached - The webpage at  might be temporarily down or it may have moved permanently to a new web address." even though I am supposedly serving an HTTP on that port. Maybe I'm just making a simple mistake.

**Comment by alexyuisingwu** [comment]
Are you creating your local HTTP server in the project folder? As long as your server can serve index.html, you should be able to reach the page.

You can also just use the demo page (listed under live demo).

The solver can only optimally solve 4x4 puzzles. The problem space and solving complexity increases exponentially (or something like that, I don't remember off the top of my head), so solutions for larger puzzles require substantially larger pattern databases (and/or other algorithms). Last I remembered, state-of-the-art solutions reached 5x5 or 6x6 puzzles, with solve-time in a couple of hours? Memory/storage requirements balloon quickly however.

It's not something I'm currently interested in implementing, so the solver will likely stay limited at 4x4.

**Comment by jonluntzel** [comment]
I got it working on the server. The issue was I was trying > 4x4 and so the solution was not being printed (sorry for all the bother). Have you tested the maximum that the strategic solver can reach a solution on?

**Comment by alexyuisingwu** [comment]
Strategic solver's algorithm should be O(n) where n is the number of tiles, iirc.

It should only be limited by your browser's resources.

The strategic solver uses a fairly simple strategy described on the README. It doesn't provide an optimal solution.
